---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-briefing-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: the-briefing
  template:
    metadata:
      labels:
        app: the-briefing
    spec:
      containers:
      - name: the-briefing-container
        image: wiameelyakini/the-briefing
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: the-briefing-service
spec:
  type: LoadBalancer
  selector:
    app: the-briefing
  ports:
  - port: 80
    targetPort: 3000
